<a href="https://colab.research.google.com/github/divyanshiparmar568/aiml-bootcamp1-2026/blob/main/b1_session3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
marks=[78,84,62]
avg=sum(marks)/len(marks)
print(avg)

74.66666666666667


In [ ]:
def calculate_average(marks):
  return sum(marks)/len(marks)

student_marks=[78,84,62]
average = calculate_average(student_marks)
print(average)

74.66666666666667


In [ ]:
def check_result(marks):
    if marks < 40:
        return "Fail"
    else:
        return "Pass"
marks = int(input("Enter marks: "))
print(check_result(marks))


Enter marks: 68
Pass


In [ ]:
import numpy as np
marks=np.array([78,84,62])
print(marks +10)

[88 94 72]


In [ ]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
print(arr.shape)

matrix=np.array([
    [10,20,30],[40,50,60]
])
print(matrix)
print(matrix.shape)

[10 20 30 40]
(4,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [ ]:
arr = np.array([78, 91, 55, 72, 40, 88])

print("Top 2 marks:", np.sort(arr)[-2:])
print("Indices of sorted:", np.argsort(arr))
print("Unique values:", np.unique(arr))


In [ ]:
from google.colab import files
uploaded = files.upload()

# rename inside Colab (in /content/)
!mv /content/session4_dummy_students_data.csv.xls /content/session4_dummy_students.csv

import pandas as pd
df = pd.read_csv("/content/session4_dummy_students.csv")
print(df.head())


Saving session4_dummy_students_data.csv.xls to session4_dummy_students_data.csv.xls
   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69   
1         102   Diya   16    Delhi    91       88       94   
2         103  Kabir   17  Mathura    55       61       58   
3         104  Meera   16    Noida    72       79       81   
4         105  Rohan   17   Mumbai    40       52       47   

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9   
1                  96                    11                     10   
2                  75                     5                      6   
3                  89                     7                      8   
4                  68                     3                      5   

   final_project_score  
0                   82  
1                   93  
2                   60  
3                   78

In [ ]:
import pandas as pd
df = pd.read_csv("/content/session4_dummy_students.csv")
df['avg'] = df[['math', 'science', 'english']].mean(axis=1)
avg = df['avg'].to_numpy()
attendance = df['attendance_percent'].to_numpy()
city = df['city'].to_numpy()
top_students = df[avg > 85]
low_attendance = df[attendance < 75]
from_mathura = df[city == "Mathura"]

print(top_students)
print(low_attendance)
print(from_mathura)


    student_id    name  age   city  math  science  english  \
1          102    Diya   16  Delhi    91       88       94   
5          106    Sara   16  Delhi    88       93       90   
7          108  Ananya   16  Noida    95       92       89   
13         114   Priya   16  Delhi    89       86       91   
15         116    Riya   16  Noida    92       90       96   

    attendance_percent  study_hours_per_week  assignments_submitted  \
1                   96                    11                     10   
5                   97                    10                     10   
7                   94                    12                     10   
13                  95                    10                     10   
15                  98                    13                     10   

    final_project_score        avg  
1                    93  91.000000  
5                    95  90.333333  
7                    91  92.000000  
13                   92  88.666667  
15             

In [ ]:
df['average'] = df[['math', 'science', 'english']].mean(axis=1)
df['result'] = np.where(df['average'] >= 40, 'Pass', 'Fail')

print("Class Average:", df['average'].mean())
print("Highest Average:", df['average'].max())
print("Lowest Average:", df['average'].min())

top_students = df[df['average'] == df['average'].max()]
print("Top Student:", top_students)

low_attendance = df[df['attendance_percent'] < 75]
print("Low Attendance:", low_attendance)

low_assignments = df[df['assignments_submitted'] < 6]
print("Low Assignments:", low_assignments)

df.to_csv("session4_student_report.csv", index=False)


Class Average: 71.35000000000001
Highest Average: 92.66666666666667
Lowest Average: 40.666666666666664
Top Student:     student_id  name  age   city  math  science  english  attendance_percent  \
15         116  Riya   16  Noida    92       90       96                  98   

    study_hours_per_week  assignments_submitted  final_project_score  \
15                    13                     10                   96   

          avg    average result  
15  92.666667  92.666667   Pass  
Low Attendance:     student_id    name  age     city  math  science  english  \
4          105   Rohan   17   Mumbai    40       52       47   
8          109  Vivaan   17   Mumbai    48       57       51   
12         113     Dev   17   Mumbai    35       45       42   
18         119    Yash   17  Mathura    43       49       46   

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5   
8                   71         

In [ ]:
df["average"] = df[["math", "science", "english"]].mean(axis=1)
df["result"] = df["average"].apply(lambda x: "Pass" if x >= 40 else "Fail")

print("Class average:", df["average"].mean())
print("Highest average:", df["average"].max())
print("Lowest average:", df["average"].min())

top_avg = df["average"].max()
print("Top student(s):")
print(df[df["average"] == top_avg][["name", "average"]])

print("Students with attendance below 75:")
print(df[df["attendance_percent"] < 75][["name", "attendance_percent"]])

print("Students with fewer than 6 assignments:")
print(df.columns)
print(df[df["assignments_submitted"] < 6][["name", "assignments_submitted"]])

df.to_csv("session4_student_report.csv", index=False)


Class average: 71.35000000000001
Highest average: 92.66666666666667
Lowest average: 40.666666666666664
Top student(s):
    name    average
15  Riya  92.666667
Students with attendance below 75:
      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66
Students with fewer than 6 assignments:
Index(['student_id', 'name', 'age', 'city', 'math', 'science', 'english',
       'attendance_percent', 'study_hours_per_week', 'assignments_submitted',
       'final_project_score', 'avg', 'average', 'result'],
      dtype='object')
     name  assignments_submitted
4   Rohan                      5
12    Dev                      4
18   Yash                      5
